---
- hosts: all
  become: yes
  tasks:
     - name: installing apache server.....
       apt:
         name: apache2
         state: present
       service:
         name: apache2
         state: started
         enabled: yes
