---
- hosts: webservers
  become: yes
  tasks:
    - name: installing apache server...
      apt:
              name: apache2
              state: present
    - name: start apache
      service:
              name: apache2
              state: started
